### ISSUE TITLE
Rename too generic units

### ISSUE THREAD

**Issue by Alexey-T** [jdelauney/TGIFViewer#1]
you have too generic unit names: TypeHelpers, uFastBitmap. 
some apps may have this names.
you can use prefix uGif here.

**Comment by jdelauney** [comment]
Ok i'll do it

**Comment by jdelauney** [comment]
Ok i've not read correctly

uFastBitmap, and TypesHelpers can be use for others projects or applications they are not specific to the GIFViewer component. I use TypeHelpers in many of my applications and project
uFastBitmap is a light weigth unit of my big project.

**Comment by Alexey-T** [comment]
maybe then use names: DelauneyFastBitmap, DelauneyTypeHelpers?
