### ISSUE TITLE
Source Attribution missing or inaccurate

### ISSUE THREAD

**Issue by andersmelander** [jdelauney/TGIFViewer#10]
Parts of this library is obviously based on TGIFImage by Anders Melander (me) and while the LZW decoder is vaguely attributed to "GraphicEx" (which is MPL licensed), the fact is that Mike Lischke (the author of GraphicEx) copied the LZW decoder from TGIFImage, so that part is also based on TGIFImage.

This fact should be documented in the source code somehow.

For example:
_Based in part on TGIFImage, Copyright (c) 1997-99 Anders Melander._

**Comment by jdelauney** [comment]
Sorry i didn't take care of your TGifImage component.  added in uGifViewer unit
many resources found on web and credits are very obscurs It's like the story of the egg and the chicken

BTW it's fixed

Best regards
