### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by bpranoto** [jdelauney/TGIFViewer#12]
There are still memory leaks on TGifViewer.

Environment:
Compiler: Lazarus 2.0.12/FPC 3.2.0
O/S: Linux ubuntu 18.04/64bits

Step to reproduce:

1. Download the attached project
2. Set the compilation option to use heaptrc
3. Compile and run the project
4. Close the program

Inspect the heaptrc output, you'll see a lot of memory leaks.

I have tracked all the bugs and attach the patch file to fix these bugs. 
[tgifviewer_memory_leak.zip](https://github.com/jdelauney/TGIFViewer/files/6367196/tgifviewer_memory_leak.zip)
[tgifviewer_memory_leak.fix.diff.txt](https://github.com/jdelauney/TGIFViewer/files/6367203/tgifviewer_memory_leak.fix.diff.txt)

**Comment by jdelauney** [comment]
Thank you bpranoto, i've applied your patch 👍
