### ISSUE TITLE
Msgbox not in english

### ISSUE THREAD

**Issue by Alexey-T** [jdelauney/TGIFViewer#7]
MessageDlg('Le fichier '+aFileName+' est introuvable !', mtError, [mbOK],0);

need english text.

**Comment by Alexey-T** [comment]
dsInvalidBufferSize: AddError('Image #' + CurrentFrameIndex.ToString + ' : La taille du tampon d''entrée et de sortie sont invalides ( Taille <= 0)');
        dsInvalidInputBufferSize: AddError('Image #' + CurrentFrameIndex.ToString + ' : La taille du tampon d''entrée est invalide ( Taille <= 0)');
        dsInvalidOutputBufferSize: AddError('Image #' + CurrentFrameIndex.ToString + ' : La taille du tampon de sortie est invalide ( Taille <= 0)');
        dsBufferOverflow: AddError('Image #' + CurrentFrameIndex.ToString + ' : Le décodeur s''est arrêté pour empêcher un débordement de tampon');

**Comment by jdelauney** [comment]
Yes i'll see how to include translate message with i18n in a package

**Comment by jdelauney** [comment]
It's same issue for us French usesr when we have only text in english :wink:
