### ISSUE TITLE
Problem with few gifs

### ISSUE THREAD

**Issue by j2969719** [jdelauney/TGIFViewer#9]
when i try to load [these gifs](http://rgho.st/7rRd2QKZl) via GifView, i get a corrupt data error
can you check what wrong with these files?

**Comment by jdelauney** [comment]
I can't download the zip please use another server rghost.ru is not secure.
Thanks

**Comment by j2969719** [comment]
one of these files can be found on [imgur](https://imgur.com/gallery/kyjUqQm)

**Comment by jdelauney** [comment]
This work work perfectly but the file is corrupted. the first image is bad encoded

![2018-07-02_152952](https://user-images.githubusercontent.com/29355534/42167037-15b9fbb0-7e0d-11e8-9e56-9029b5deb431.jpg)
![imgurtest](https://user-images.githubusercontent.com/29355534/42167057-209d52e8-7e0d-11e8-8123-188a3f8f3ce9.gif)
I found the first gif is the same image is corrupted but you can see it.  Don't found the third gif.

Perhaps i'll add an option for deleting automaticaly corrupted frame
